_inputs:
  _id:
    type: disabled
    instance_value: UUID
  blurb:
    type: textarea
  author_staff_member:
    type: select
    options:
      values: collections.staff_members
      value_key: _id
  live_domain_url:
    comment: "Remove any '/' at the end of the URL so your domain looks like this - 'https://example.com'"
  website_description_text:
    comment: Used for search engine optimisation and sharing on social media
  social_media_share_image:
    comment: 1200x675px
  twitter_handle:
    comment: E.g. @username
  large_bookmark_icon_image:
    comment: 32x32px
  small_bookmark_icon_image:
    comment: 16x16px

_select_data:
  page_themes:
    - Light
    - Dark
  alignments:
    - Left
    - Center
    - Right
  link_types:
    - Text
    - Button
  website_themes:
    - 'Hydra'
    - 'Justice'
    - 'Cause'
    - 'Urban'
  component_themes:
    - 'Light'
    - 'Dark'
    - 'Branded'

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_structures:
  content_blocks:
    style: modal

collections_config:
  pages:
    name: 'Pages'
    icon: 'web'
    singular_name: 'Page'
    _slug: 'pages'
    output: true
    permalink: /:title/
  staff_members:
    name: 'Staff Members'
    icon: supervisor_account
    _enabled_editors:
      - data
    singular_name: 'Staff Member'
    _slug: 'staff_members'
    output: false

# Make sure you add any new collections here for them to show in CloudCannon
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blog
    collections:
      - posts
      - drafts
      - staff_members
  - heading: Settings
    collections:
      - data