light_theme_settings:
  page_color: "#ffffff"
  component_alt_color: "#f5f5f5"
  brand_color: "#4182e4"
  headings_color: "#000000"
  text_color: "#666666"
  light_text_color: "#ffffff"
  link_color: "#00a4ca"
  button_fill_color: "#4182e4"
  button_fill_text_color: "#ffffff"
  tag_color: '#eeeeee'
  footer_color: '#2b2b40'
dark_theme_settings:
  page_color: "#131313"
  component_alt_color: "#1a1a1a"
  brand_color: "#202020"
  headings_color: "#ffffff"
  text_color: "#c4c4c4"
  light_text_color: "#ffffff"
  link_color: "#00a4ca"
  button_fill_color: "#737373"
  button_fill_text_color: "#ffffff"
  tag_color: '#444444'
  footer_color: '#000000'
body_font: 'San Francisco'