plugins:
  - jekyll-bookshop
  - jekyll-postcss-v2
  - jekyll-archives
  - jekyll-feed

jekyll-archives:
  enabled:
    - categories

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../component-library/

exclude:
  - postcss.config.js
  - node_modules

permalink: pretty

collections_dir: collections
collections:
  pages:
    output: true
    permalink: /:title/
  staff_members:
    output: false
  clients:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      _options:
        content: &content_defaults
          uploads_dir: "/images/uploads/:title"
          width: 1180
          height: 900
          format: p h1 h2 h3 h4 h5 h6 div
          styles: /assets/cms-styles.css
          undo: true
          redo: true
          left: align-to-left
          center: align-to-center
          right: align-to-right
          justify: justify
          bold: true
          italic: true
          underline: true
          strike: true
          subscript: false
          superscript: false
          blockquote: true
          table: true
          copyformatting: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          outdent: false
          indent: false
          image: true
          link: true
          embed: true
        content_text:
          *content_defaults
        content_html:
          *content_defaults
        text:
          *content_defaults
        text_html:
          *content_defaults
  -
    scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: clients
    values:
      layout: client