source "https://rubygems.org"


group :jekyll_plugins do
  gem "jekyll-bookshop", "3.3.0"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-feed', '~> 0.15.1'
end
