title: Jekyll AC Testing Template

plugins:
  - jekyll-bookshop
  - bookshop-array-structures
  - jekyll-postcss-v2

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../hydra-components

exclude:
  - postcss.config.js
  - node_modules

collections_dir: 'collections'

collections:
  web_pages:
    name: 'Web Pages'
    _icon: 'web'
    _singular_name: 'Page'
    output: true
    permalink: /:title/

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

_select_data:
  page_themes:
    - Light
    - Dark
  alignments:
    - Left
    - Center
    - Right
  link_type:
    - Text
    - Button

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      _options:
        content: &content_defaults
          uploads_dir: "/images/uploads/:title"
          width: 1180
          height: 900
          format: p h1 h2 h3 h4 h5 h6 div
          styles: /assets/css/cms-styles.css
          undo: true
          redo: true
          left: align-to-left
          center: align-to-center
          right: align-to-right
          justify: justify
          bold: true
          italic: true
          underline: true
          strike: true
          subscript: false
          superscript: false
          blockquote: true
          table: true
          copyformatting: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          outdent: false
          indent: false
          image: true
          link: true
          embed: true
        content_text:
          *content_defaults
        content_html:
          *content_defaults
        text:
          *content_defaults
        text_html:
          *content_defaults
  -
    scope:
      type: web_pages
      path: _web_pages/index.html
    values:
      permalink: /