source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", ">= 2.0.0.pre.alpha"
  gem "bookshop-array-structures", ">= 2.0.0.pre.alpha"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-postcss-v2'
end
