source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-bookshop", ">= 2.0.0.pre.alpha"
  gem "bookshop-array-structures", ">= 2.0.0.pre.alpha"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-feed', '~> 0.15.1'
  gem 'jekyll-seo-tag', '~> 2.7.1'
  gem 'jekyll-sitemap', '~> 1.4.0'
end
