website_name: Hydra
live_domain_url:
website_description_text:
social_media_share_image:
twitter_handle:
icons:
  small_bookmark_icon_image: /assets/favicon-16x16.png
  large_bookmark_icon_image: /assets/favicon-32x32.png
  mobile_icon_image: