light_theme_settings:
  page_color: "#ffffff"
  component_alt_color: "#f5f5f5"
  brand_color: "#4182e4"
  headings_color: "#000000"
  text_color: "#666666"
  light_text_color: "#ffffff"
  link_color: "#00a4ca"
  button_fill_color: "#4182e4"
  button_fill_text_color: "#ffffff"
dark_theme_settings:
  page_color: "#222222"
  component_alt_color: "#f5f5f5"
  brand_color: "#4182e4"
  headings_color: "#000000"
  text_color: "#666666"
  light_text_color: "#ffffff"
  link_color: "#00a4ca"
  button_fill_color: "#4182e4"
  button_fill_text_color: "#ffffff"