[component]
array_structures = [ "components" ]
label = "Button"
description = "Generic customisable button"
icon = "wysiwyg"
tags = ["Generic"]

[props]
label = "Get Started Free"
link_url = "/sign-up/"
variant.select = ["Transparent", "Filled"]
open_in_new_tab = false